### ISSUE TITLE
can this project used to flash STM32F103C8T6 ?

### ISSUE THREAD

**Issue by kprasadvnsi** [ataradov/embedded-swd#2]
I am trying to port it to my custom microcontroller but it got stuck at "Erasing entire device..." when flashing STM32F103C8T6.

do I need to change dap target values?

**Comment by ataradov** [comment]
You do need to add STM32 support. It would be entirely new target_xxx.c file. DAP part is probably fine if you've got to the erasing function at all.

**Comment by kprasadvnsi** [comment]
any repo that implements stm32 target and DAP interface similar to yours?

**Comment by ataradov** [comment]
Not that I'm aware of. The port should not be too hard - just copy one of the targets and replace all device-specific stuff. 

Otherwise just use OpenOCD. It is a bit trickier to setup, but probably supports STM32 out of the box.

**Comment by kprasadvnsi** [comment]
is this implementation compatible with your repo?
https://github.com/tthe207/DP-SW

**Comment by ataradov** [comment]
~~This is not event remotely the same thing. This is implementation of the actual SWD protocol.~~

~~EDBG is the project that works with CMSIS-DAP debuggers. The project you are referring to is what you need to make your own debugger.~~ I mixed up the projects.

What exactly do you want to achieve?

**Comment by ataradov** [comment]
Although you can look up the logic of functions like SWD_FlashErasePage() and implement similar functionality using DAP functions from this project. But it is much easier to just read the user manual for the processor.

**Comment by kprasadvnsi** [comment]
I have a RISC-V microcontroller which I am using to program STM32. The problem is that it needs to be self-contained binary with STM32 firmware as payload and SWD logic.

**Comment by ataradov** [comment]
Ok, I actually confused the projects (I though we were in EDBG project). This (my) project is close to what you want. But you still have to re-implement stuff from dap_target.c. But it looks like the project you are linking is much closer. All you need to implement there is IO functions.

**Comment by ataradov** [comment]
Get your code to the point where you can read/write RAM of the target MCU. From from that to programming the flash is very easy.

**Comment by kprasadvnsi** [comment]
I will try to port DP-SW project. Thanks for all your help on this issue.
