### ISSUE TITLE
dap_target_write_page address parameter

### ISSUE THREAD

**Issue by ooxi** [ataradov/embedded-swd#3]
I am trying to understand the semantic of the `addr` parameter passed to the [`dap_target_write_page`](https://github.com/ataradov/embedded-swd/blob/master/dap_target.c#L109) function.

Is this the page number or the absolute address of the first flash byte to be written (and has thus be aligned to page boundaries)?

Moreover I'm wondering about the significance of [0x8000](https://github.com/ataradov/embedded-swd/blob/master/main.c#L142) passed to the function. Does this have to do something with [top of RAM](https://github.com/ataradov/mcu-starter-projects/blob/master/samd21/linker/samd21j18.ld#L32) of the target chip?

What I'm trying to do is to extend your example to not only flash a single page, but to flash a hole binary to a target.

**Comment by ooxi** [comment]
I most likely figured it out, `addr` is the position of the absolute position of the first byte in flash to be written, but has to be aligned to page boundaries.

**Comment by ataradov** [comment]
It is absolute address. But actually it is the offset from the section start. It makes no difference for the main flash, but may matter for RWW sections.

The ADDR register does not have full 32-bits implemented, so it all works out in the end anyway.
