### ISSUE TITLE
Informational request - Why is the clock implemented with first low, then high?

### ISSUE THREAD

**Issue by mrquincle** [ataradov/embedded-swd#6]
In the code I see that writes and reads are starting with a clock low: 

```
static void dap_swd_write(uint32_t value, int size)
{
  for (int i = 0; i < size; i++)
  {
    DAP_CONFIG_SWDIO_write(value & 1);
    DAP_CONFIG_SWCLK_clr();
    dap_delay_loop();
    DAP_CONFIG_SWCLK_set();
    dap_delay_loop();
    value >>= 1;
  }
}
```

If I look in the ARM documentation, https://documentation-service.arm.com/static/5f900a61f86e16515cdc0610?token= I see that in the figure they start with the clock high.

![image](https://user-images.githubusercontent.com/1428585/166653193-5b513d64-e64e-442c-a646-342dcfadcbc3.png)

However, I have seen more code like yours that starts with the clock low. For example at https://github.com/atc1441/ESP32_nRF52_SWD/blob/main/ESP32_SWD_WIFI/swd.cpp.

Maybe it doesn't matter but I have the idea that you guys know what you are doing. So, hereby my question: Why is the clock implemented with first a half cycle LOW and then a half cycle HIGH.

I know this is not an active project, but it would be super great to learn to know why!

**Comment by ataradov** [comment]
You start with the clock high, as it is high by default. I set the IO value first, since H->L transition does not do anything and doing it in this order lets the IO line to settle. The action is taken on the L->H edge and then a new value is set.

Technically it means that hold time on the IO may be low if the delay loop is fast, but in practice it is way longer than necessary and setup time is far more important, as it is influenced by the capacitance of the wires and traces.

But all of this is highly theoretical. It does not really matter at those speeds. I just picked one and stuck with it.

**Comment by ataradov** [comment]
Note that at the end of the loop you also exit with clock being high, and the next call to this function would see starting level as high.

**Comment by mrquincle** [comment]
Ah, nice to know! I'm not using the code as is, but using it as inspiration on another embedded platform, hence good to know when speeds are indeed higher.

I'm now playing around with getting something stable.

![image](https://user-images.githubusercontent.com/1428585/166888427-45759d5b-0b05-43dd-98e5-af26f4ab198e.png)

It's not yet responding, but I guess I have to fine tune better. I've now done a clock on 250k (I actually don't know how slow it can be). For now it seems I've to pay more attention to how many clock cycles instructions costs and make sure the entire sequence is handled at once. I'm just sprinkling some nops here and there to make that happen. :-) 

It's fun!

**Comment by ataradov** [comment]
The clock can be very slow. Vendors usually define something like 1-2 kHz as a minimum, but I see no reason why it could not be even slower.

There is no response to the JTAG-SWD switch sequence, the first response you get is to the read idcode command.

**Comment by mrquincle** [comment]
Thanks a lot for your insight!! Much appreciated!
